### ISSUE TITLE
Please give an example workflow

### ISSUE THREAD

**Issue by wardensc2** [asagi4/ComfyUI-NPNet#1]
Hi @asagi4 

Can you give us an example workflow since I already install the node but don't know what to do to run Golden Noise

Thank in advance

**Comment by asagi4** [comment]
If you just follow the node types, the workflow is pretty obvious. You just need to connect the output `NOISE` into a `KSampler (custom)` and fill in everything else.

For the input, just use `RandomNoise` and the positive prompt you pass into KSampler

**Comment by pivtienduc** [comment]
Thank you so much
